version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/Uniforum-server/app
    environment:
      - NODE_ENV=development

  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/Uniforum-client/app
      - /Uniforum-client/app/node_modules
    environment:
      - NODE_ENV=development
